### ISSUE TITLE
[Bug][DevOps] Frontend build fails

### ISSUE THREAD

**Issue by marchev** [daritelska-platforma/frontend#233]
As the issue title states, the frontend build fails on the `master` branch.

**Steps to reproduce:**
1. `git clone git@github.com:daritelska-platforma/frontend.git && cd frontend`
2. `ln -s .env.example .env`
3.  `docker-compose up -d `

**Expected result:**
The project is built successfully.

**Actual result:**
The `frontend` module build fails.

**Environment:**
- OS: **macOS Big Sur**
- Docker Desktop: **v3.3.3 (64333)**
- Docker Engine: **v20.10.6**
- Docker Compose: **v1.29.1**

**Logs:**
<details>
  <summary>Click to expand!</summary>

```
Docker Compose is now in the Docker CLI, try `docker compose up`

Building frontend
[+] Building 34.5s (9/10)
 => [internal] load build definition from Dockerfile                                                                                                     0.0s
 => => transferring dockerfile: 37B                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/node:14-alpine                                                                                        1.4s
 => [base 1/4] FROM docker.io/library/node:14-alpine@sha256:f07ead757c93bc5e9e79978075217851d45a5d8e5c48eaf823e7f12d9bbc1d3c                             0.0s
 => [internal] load build context                                                                                                                        0.0s
 => => transferring context: 14.12kB                                                                                                                     0.0s
 => CACHED [base 2/4] WORKDIR /app                                                                                                                       0.0s
 => CACHED [base 3/4] COPY package.json yarn.lock /app/                                                                                                  0.0s
 => CACHED [base 4/4] RUN apk --no-cache add curl                                                                                                        0.0s
 => ERROR [dependencies 1/1] RUN yarn install --production &&   cp -R node_modules /prod_node_modules &&   yarn install --production=false              33.0s
------
 > [dependencies 1/1] RUN yarn install --production &&   cp -R node_modules /prod_node_modules &&   yarn install --production=false:
#9 0.381 yarn install v1.22.5
#9 0.435 [1/4] Resolving packages...
#9 0.566 [2/4] Fetching packages...
#9 23.66 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#9 23.66 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#9 23.67 [3/4] Linking dependencies...
#9 23.67 warning "next-auth > @next-auth/prisma-legacy-adapter@0.0.1-canary.127" has unmet peer dependency "@prisma/client@^2.16.1".
#9 23.67 warning " > typewriter-effect@2.17.0" has incorrect peer dependency "react@16.x".
#9 23.67 warning " > typewriter-effect@2.17.0" has incorrect peer dependency "react-dom@16.x".
#9 29.76 [4/4] Building fresh packages...
#9 30.24 error /app/node_modules/bufferutil: Command failed.
#9 30.24 Exit code: 1
#9 30.24 Command: node-gyp-build
#9 30.24 Arguments:
#9 30.24 Directory: /app/node_modules/bufferutil
#9 30.24 Output:
#9 30.24 gyp info it worked if it ends with ok
#9 30.24 gyp info using node-gyp@5.1.0
#9 30.24 gyp info using node@14.17.0 | linux | arm64
#9 30.24 gyp ERR! find Python
#9 30.24 gyp ERR! find Python Python is not set from command line or npm configuration
#9 30.24 gyp ERR! find Python Python is not set from environment variable PYTHON
#9 30.24 gyp ERR! find Python checking if "python" can be used
#9 30.24 gyp ERR! find Python - "python" is not in PATH or produced an error
#9 30.24 gyp ERR! find Python checking if "python2" can be used
#9 30.24 gyp ERR! find Python - "python2" is not in PATH or produced an error
#9 30.24 gyp ERR! find Python checking if "python3" can be used
#9 30.24 gyp ERR! find Python - "python3" is not in PATH or produced an error
#9 30.24 gyp ERR! find Python
#9 30.24 gyp ERR! find Python **********************************************************
#9 30.24 gyp ERR! find Python You need to install the latest version of Python.
#9 30.24 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#9 30.24 gyp ERR! find Python you can try one of the following options:
#9 30.24 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#9 30.24 gyp ERR! find Python   (accepted by both node-gyp and npm)
#9 30.24 gyp ERR! find Python - Set the environment variable PYTHON
#9 30.24 gyp ERR! find Python - Set the npm configuration variable python:
#9 30.24 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#9 30.24 gyp ERR! find Python For more information consult the documentation at:
#9 30.24 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#9 30.24 gyp ERR! find Python **********************************************************
#9 30.24 gyp ERR! find Python
#9 30.24 gyp ERR! configure error
#9 30.24 gyp ERR! stack Error: Could not find any Python installation to use
#9 30.24 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
#9 30.24 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
#9 30.24 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
#9 30.24 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
#9 30.24 gyp ERR! stack     at exithandler (child_process.js:326:5)
#9 30.24 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:338:5)
#9 30.24 gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
#9 30.24 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
#9 30.24 gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
#9 30.24 gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
#9 30.24 gyp ERR! System Linux 5.10.25-linuxkit
#9 30.24 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#9 30.24 gyp ERR! cwd /app/node_modules/bufferutil
#9 30.24 gyp ERR! node -v v14.17.0
#9 30.24 gyp ERR! node-gyp -v v5.1.0
#9 30.24 gyp ERR! not ok
#9 30.24 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install --production &&   cp -R node_modules /prod_node_modules &&   yarn install --production=false]: exit code: 1
ERROR: Service 'frontend' failed to build : Build failed
```
</details>

**Comment by kachar** [comment]
Seems related https://stackoverflow.com/questions/59470406/how-to-solve-could-not-find-any-python-installation-to-use-with-docker-node-al
